const scholarships = [
  {
    name: "National Scholarship Portal",
    provider: "Government of India",
    state: "All India",
    category: "Student",
    course: "Any",
    gender: "Any",
    incomeLimit: 250000,
    eligibility: "Students with family income below ₹2.5 lakh",
    benefits: "Financial assistance",
    documents: ["Aadhaar", "Income Certificate", "Marksheet"],
    applyStart: "July",
    applyEnd: "October",
    officialLink: "https://scholarships.gov.in",
    keywords: ["student", "scholarship", "college"],
  },

  {
    name: "Swami Vivekananda Merit Cum Means Scholarship",
    provider: "West Bengal Government",
    state: "West Bengal",
    category: "Student",
    course: "UG/PG",
    gender: "Any",
    incomeLimit: 250000,
    eligibility: "WB students with required marks",
    benefits: "₹12000-₹96000",
    documents: ["Income", "Marksheet"],
    applyStart: "August",
    applyEnd: "November",
    officialLink: "https://svmcm.wbhed.gov.in",
    keywords: ["engineering", "wb", "student"],
  },

  {
    name: "AICTE Pragati Scholarship",
    provider: "AICTE",
    state: "All India",
    category: "Engineering",
    course: "Technical",
    gender: "Female",
    incomeLimit: 800000,
    eligibility: "Girls studying technical courses",
    benefits: "₹50000",
    documents: ["Aadhaar", "Admission Proof"],
    applyStart: "September",
    applyEnd: "November",
    officialLink: "https://aicte-india.org",
    keywords: ["engineering", "girl"],
  },

  {
    name: "AICTE Saksham Scholarship",
    provider: "AICTE",
    state: "All India",
    category: "Engineering",
    course: "Technical",
    gender: "Any",
    incomeLimit: 800000,
    eligibility: "Specially abled students",
    benefits: "₹50000",
    documents: ["Disability Certificate"],
    applyStart: "September",
    applyEnd: "November",
    officialLink: "https://aicte-india.org",
    keywords: ["disabled", "engineering"],
  },

  {
    name: "Oasis Scholarship",
    provider: "West Bengal Government",
    state: "West Bengal",
    category: "SC/ST/OBC",
    course: "Any",
    gender: "Any",
    incomeLimit: 250000,
    eligibility: "SC/ST/OBC students",
    benefits: "Scholarship amount varies",
    documents: ["Caste Certificate", "Income Certificate"],
    applyStart: "July",
    applyEnd: "December",
    officialLink: "https://oasis.gov.in",
    keywords: ["obc", "sc", "st"],
  },
];

export default scholarships;
